# Generated by Django 4.2.5 on 2023-09-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approvals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('dependents', models.IntegerField()),
                ('applicantincome', models.IntegerField()),
                ('coapplicantincome', models.IntegerField()),
                ('loanamount', models.IntegerField()),
                ('loanterm', models.IntegerField()),
                ('credithistory', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=15)),
                ('married', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=5)),
                ('education', models.CharField(choices=[('graduate', 'GRADUATE'), ('not graduate', 'NOT GRADUATE')], max_length=15)),
                ('selfemployed', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=5)),
                ('propertyarea', models.CharField(choices=[('rural', 'RURAL'), ('semiurban', 'SEMIURBAN'), ('urban', 'URBAN')], max_length=15)),
            ],
        ),
    ]
